#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

$DIR/src/server.js --socket $DIR/net/dataserve.sock --env $DIR/.env_dev --config $DIR/config/exampleBlogModules.json
#$DIR/src/server.js --socket $DIR/net/dataserve.sock --env $DIR/.env_dev
#$DIR/src/server.js --port 6380 --env ./.env_dev
